args<-commandArgs(TRUE)
StartTime<-Sys.time()
#path = "c:\Program Files\r\R-3.0.1\bin\x64"
#cd D:\ICRISAT\Work\Analysis\Work\ISMU\ISMU  
TFile<-tempfile()
#TFile
sink(TFile)

GetRFileName <- function (start = "RES_")
{
  paste(start, substring(date(), 5, 7), substring(date(), 9, 10), "_", substring(date(), 12, 13), substring(date(), 15, 16), substring(date(), 18, 19), abs(round(rnorm(1),3)), sep = "")  
}

require("genetics", quietly=T)
require(R2HTML)

#args <- c("C:/Users/admin/Documents/1/","Result_014534-3.htm", "GSTemp.txt")

AWD       		   <- args[1]
ARFILE    		   <- args[2]
ATEMP_FILE_CORR    <- args[3]   # Will Store: Method, Coorel and  P value

oldwd<-setwd(AWD)



# Write All Correlation and P Value

Res<-read.table(ATEMP_FILE_CORR, header=T)

TRes<-HTML.title(paste("Summary of Selected GS Methods"), HR=3, file=ARFILE, Append=T)

TRes<-HTML(Res, file=ARFILE, Append=T)

# Write Time and Logo
TRes<-HTML("<hr/><p align=center> ", file=ARFILE, Append=T)
TRes<-HTML(paste("Results Generated by ISMU 3.0 : ", format(Sys.time(), "%a %b %d %X %Y")), file=ARFILE, Append=T)
#TRes<-HTMLEndFile(file=ARFILE)
TRes<-HTML("</body></html>", file=ARFILE, Append=T)
# TRes<-HTML("<table border=1><tr class= firstline><td>Method</td><td>Correlation</td><td>Prob>t</td></tr>", file=ARFILE, Append=T)
# TRes<-HTML(paste("<tr><td>", SelectedMethod, "</td><td>", round(correl$estimate, SG), "</td><td>", round(correl$p.value, SG),"</td></tr>"), file=ARFILE, Append=T)

#file.remove("gsdata.rdata")
sink()
setwd(oldwd)
file.remove(TFile)